services:
    fieldsets-cache:
        image: ${CONTAINER_REGISTRY:-fieldsets}/cache-plugin-redis:${REDIS_VERSION:-latest}
        build:
            context: ./
            dockerfile: ${REDIS_PLUGIN_PATH:-./}Dockerfile
            args:
                REDIS_VERSION: ${REDIS_VERSION:-latest}
                BUILD_CONTEXT_PATH: ${REDIS_PLUGIN_PATH:-./}
        container_name: fieldsets-cache
        hostname: fieldsets-cache
        tty: ${ENABLE_TERMINAL:-true}
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
        #command: redis-server --requirepass ${REDIS_PASSWORD:-fieldsets}
        environment:
            ENVIRONMENT: ${ENVIRONMENT:-dev-local}
            REDIS_HOST: ${REDIS_HOST:-0.0.0.0}
            REDIS_PORT: ${REDIS_PORT:-6379}
            PUID: ${LOCAL_UID:-1000}
            PGID: ${LOCAL_GID:-1000}
        volumes:
            - redis-data:/data
            - redis-modules:/modules
            - ${REDIS_PLUGIN_PATH:-./}plugins:/usr/local/fieldsets/plugins/
            - ${REDIS_PLUGIN_PATH:-./}lib:/usr/local/fieldsets/lib/
            - ${REDIS_PLUGIN_PATH:-./}data:/usr/local/fieldsets/data/
            - ${REDIS_PLUGIN_PATH:-./}src:/usr/local/fieldsets/apps/
            - ${REDIS_PLUGIN_PATH:-./}bin/:/usr/local/fieldsets/bin/
            - ${REDIS_PLUGIN_PATH:-./}init/:/docker-entrypoint-init.d/
            - ${REDIS_PLUGIN_PATH:-./}entrypoint.sh:/docker-entrypoint.sh

volumes:
    redis-data:
        driver: local
        name: fieldsets-cache-data
    redis-modules:
        driver: local
        name: fieldsets-cache-modules
