version: '3.7'
services:
    fieldsets-cache:
        image: ${CONTAINER_REGISTRY:-fieldsets}/cache-plugin-redis:${REDIS_VERSION:-latest}
        build:
            context: ./
            dockerfile: ${REDIS_CONFIG_PATH:-./}Dockerfile
            args:
                REDIS_VERSION: ${REDIS_VERSION:-latest}
        container_name: fieldsets-cache
        hostname: fieldsets-cache
        ports:
            - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
        #command: redis-server --requirepass ${REDIS_PASSWORD:-fieldsets}
        environment:
            REDIS_HOST: ${REDIS_HOST:-0.0.0.0}
            REDIS_PORT: ${REDIS_PORT:-6379}
        volumes:
            #- ${REDIS_CONFIG_PATH:-./}redis.conf:/etc/redis.conf
            - redis-data:/data
            - redis-modules:/modules

volumes:
    redis-data:
        driver: local
        name: fieldsets-cache-data
    redis-modules:
        driver: local
        name: fieldsets-cache-modules
