services:
    fieldsets-cache:
        volumes:
            - fieldsets-plugins:/fieldsets-plugins/
            - fieldsets-data:/fieldsets-data/
            - fieldsets-lib:/fieldsets-lib/
            - fieldsets-src:/fieldsets/